name: Pipeline de CI

on: [push, pull_request]

jobs:
  build:
    runs-on: obuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar Análise Estática (Lint)
        run: flake8 src/

      - name: Rodar Testes automatizados
        run: pytest tests/